"""Set default value for status column

Revision ID: e97b5d99633b
Revises: 
Create Date: 2024-09-03 15:29:04.949645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97b5d99633b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
